liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: uploads/cache
    driver: imagick
    data_loader: default
    filter_sets:
        list_image:
            quality: 85
            filters:
              relative_resize: { widen: 75 }
              strip: ~
        edit_image:
            quality: 85
            filters:
              relative_resize: { widen: 750 }
              strip: ~
