superrbkunstmaansocialmediabundle_instagram_authentication:
    pattern: /sksmb/instagram/generate-token
    defaults: { _controller: SuperrbKunstmaanSocialMediaBundle:InstagramAuthentication:index }
