services:
    SuperrbKunstmaanSocialMediaBundle.menu.adaptor.modules:
        class: Superrb\KunstmaanSocialMediaBundle\Helper\Menu\ModulesMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }