services:
    kunstmaan_admin.versionchecker:
        class: Superrb\KunstmaanSocialMediaBundle\VersionCheck\VersionChecker
        arguments: ['@service_container', '@kunstmaan_admin.cache']
    sb_social_media:
        class: Superrb\KunstmaanSocialMediaBundle\Service\SocialMediaService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%sb_social_media.instagram%"
            - "%sb_social_media.twitter%"
            - "%sb_social_media.tumblr%"
            - "%sb_social_media.vimeo%"
    sb_social_media_custom_form:
        class: Superrb\KunstmaanSocialMediaBundle\Form\SocialAddType
        arguments:
            - '@sb_social_media'
    SuperrbKunstmaanSocialMediaBundle.menu.adaptor.modules:
        class: Superrb\KunstmaanSocialMediaBundle\Helper\Menu\ModulesMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
        arguments:
            - '@sb_social_media'