services:
    sb_social_media:
        class: Superrb\KunstmaanSocialMediaBundle\Service\SocialMediaService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%sb_social_media.instagram%"
            - "%sb_social_media.twitter%"
            - "%sb_social_media.tumblr%"
            - "%sb_social_media.vimeo%"
    SuperrbKunstmaanSocialMediaBundle.menu.adaptor.modules:
        class: Superrb\KunstmaanSocialMediaBundle\Helper\Menu\ModulesMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
        arguments: ['@sb_social_media']