<?php

namespace Superrb\SocialMediaFeedBundle\Repository;

/**
 * SocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialRepository extends \Doctrine\ORM\EntityRepository
{
}
