<?php

namespace Superrb\KunstmaanSocialMediaBundle\Repository;

use Superrb\KunstmaanSocialMediaBundle\Entity\Setting;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the settings for Instagram
     */
    public function instagram()
    {
        $setting = $this->findOneBySocialType('instagram');

        if($setting)
        {
            return $setting;
        }

        $setting = new Setting();
        $setting->setSocialType('instagram');

        return $setting;
    }
}
